task: "classify"
network: "cnns"
model: "res_18"
model_dir: "model"
train_type: "transfer"  # or scratch
img_width: 227
img_height: 227
resume: True  # 追加学習するか
use_amp: False  # 半精度で訓練するか
record_dir: "record"
ep_iter: -1
save_ep: 5
eval_ep: 1

train:
  epoch: 30
  dataset: "AngleDetectTrain_2"
  batch_size: 30
  num_workers: 4
  batch_sampler: "image_size"
  optim: "adam"
  criterion: ""
  lr: 1e-3
  scheduler: "step_lr"
  weight_decay: 0.0
  milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
  warp_iter: 10  # 何 epoch ごとに lr を調整するか
  gamma: 0.5

test:
  dataset: "AngleDetectVal_2"
  batch_size: 20
  num_workers: 2
  batch_sampler: "image_size"
