task: "classify"
network: "cnns"
model: "inc_v3"
model_dir: "model"
train_type: "transfer" # or scratch
img_width: 299
img_height: 299
resume: True # 追加学習するか
use_amp: False # 半精度で訓練するか
optuna: True # optuna を使用して最適化するか
optuna_trials: 30
record_dir: "record"
ep_iter: -1
save_ep: 5
eval_ep: 5

train:
  epoch: 10
  dataset: "AngleDetectTrain_2"
  batch_size: 24
  num_workers: 4
  batch_sampler: ""
  optim: "adam"
  criterion: ""
  lr: 1e-3
  scheduler: "step_lr"
  weight_decay: 0.0
  milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
  warp_iter: 10 # 何 epoch ごとに lr を調整するか
  gamma: 0.5
val:
  dataset: "AngleDetectVal_2"
  batch_size: 24
  num_workers: 4
  batch_sampler: ""
test:
  dataset: "AngleDetectVal_2"
  batch_size: 24
  num_workers: 4
  batch_sampler: ""
