task: "semantic_segm"
cls_names: ["laptop", "tv"]
network: "smp"
model: "unetpp"
encoder_name: "resnet18"
model_dir: "model"
train_type: "transfer"
img_width: 224
img_height: 224
resume: True # 追加学習するか
record_dir: "record"
ep_iter: -1
save_ep: 5
eval_ep: 1
use_amp: True

train:
  epoch: 1000
  dataset: "COCO2017Train"
  batch_size: 20
  num_workers: 2
  batch_sampler: ""
  optim: "adam"
  criterion: ""
  lr: 1e-3
  scheduler: "step_lr"
  weight_decay: 0.0
  milestones: (20, 40, 60, 80, 100, 120, 160, 180, 200, 220)
  warp_iter: 50
  gamma: 0.5
  metrics: "iou"

test:
  dataset: "COCO2017Val"
  batch_size: 20
  num_workers: 2
  batch_sampler: ""
