# コンフィグ情報の記述方法については以下を参考．
# REF: https://qiita.com/Yama-to/items/587544993fb62610528a

- loop: 1
  network: "cnns"
  model: "inc_v3"
  train_type: "transfer"
  replaced_layer_num: 1
  img_width: 299
  img_height: 299
  train:
    # dataset: "AngleDetectTrain_2"
    # dataset: "SampleTest"
    batch_sampler: ""
  val:
    # dataset: "AngleDetectTrain_2"
    # dataset: SampleTrain
    batch_sampler: ""
  test:
    # dataset: "AngleDetectTrain_2"
    # dataset: "SampleTrain"
    batch_sampler: ""
- loop: 2
  network: "cnns"
  model: "vgg_16"
  train_type: "transfer"
  replaced_layer_num: 3
  img_width: 224
  img_height: 224
- loop: 3
  network: "cnns"
  model: "vgg_19"
  train_type: "transfer"
  replaced_layer_num: 3
  img_width: 224
  img_height: 224
- loop: 4
  network: "cnns"
  model: "eff_b0"
  train_type: "transfer"
  replaced_layer_num: 3
  img_width: 224
  img_height: 224
